[profile.default]
src = "src"
out = "out"
via_ir = true
libs = ["lib"]
solc = "0.8.26"
remappings = [
    "@uniswap/v2-core/=lib/v2-core/",
    "@uniswap/v2-periphery/=lib/v2-periphery/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"